In [3]:
print('Hello World')

Hello World


In [2]:
print('Can I go on Git Hub Repo')

Can I go on Git Hub Repo


In [4]:
# 1 - Import the numpy package under the name np
import numpy as np

In [5]:
# 2 - Create a null vector of size 10
null_vector = np.zeros(10) # https://numpy.org/doc/stable/reference/generated/numpy.zeros.html
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 2 - Create a null vector of size 10 (Let's try to change its data type)
null_vector = np.zeros(10, dtype= int)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# 3 - Create a vector with values ranging from 10 to 49
x = np.arange(10,50) # https://numpy.org/doc/stable/reference/generated/numpy.arange.html
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# 4 - Find the shape of previous array in question 3
x.shape # https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html#:~:text=The%20shape%20property%20is%20usually,As%20with%20numpy.

1

In [23]:
# 5 - Print the type of the previous array in question 3
x.dtype # https://numpy.org/doc/stable/reference/generated/numpy.dtype.html

dtype('int32')

In [30]:
# 6 - Print the numpy version and the configuration
print('Numpy version is',np.__version__)
print(np.show_config())

Numpy version is 1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [31]:
# 7 - Print the dimension of the array in question 3
x.ndim # https://numpy.org/doc/stable/reference/generated/numpy.ndarray.ndim.html

1

In [38]:
# 8 - Create a boolean array with all the True values
bool_arr = np.ones(10, dtype=bool) # https://numpy.org/doc/stable/reference/generated/numpy.ones.html
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [40]:
# 9 - Create a two dimensional array
two_d_arr = np.arange(10).reshape(2,5) # https://numpy.org/doc/stable/reference/generated/numpy.reshape.html
two_d_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
# 9 - Create a two dimensional array
# https://numpy.org/doc/stable/reference/generated/numpy.array.html
two_d_arr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
two_d_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [45]:
# 9 - Create a two dimensional array
x = np.arange(10)
x
y = np.arange(10,20)
y
two_d_arr = np.array([x,y])
two_d_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [53]:
# 9 - Create a two dimensional array
# https://numpy.org/doc/stable/reference/random/index.html
x = np.random.rand(10).reshape(2,5)
x

array([[0.95553775, 0.51964908, 0.22350665, 0.81285491, 0.60640809],
       [0.80377518, 0.38697976, 0.64625894, 0.30863401, 0.82516182]])

In [54]:
# 10 - Create a three dimensional array
three_d_arr = np.arange(8).reshape(2,2,2)
three_d_arr


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
# 10 - Create a three dimensional array
three_d_arr = np.array([ [[1,2,3],[4,5,6]], [[6,5,4],[3,2,1]] ])
three_d_arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [62]:
# 10 - Create a three dimensional array
three_d_arr = np.random.rand(27).reshape(3,3,3)
three_d_arr

array([[[0.59409984, 0.18378778, 0.01446873],
        [0.0275978 , 0.28873459, 0.87136217],
        [0.05968443, 0.33016941, 0.95182061]],

       [[0.56502682, 0.15803391, 0.22493604],
        [0.27812862, 0.7063894 , 0.11457672],
        [0.06437019, 0.30913878, 0.38537361]],

       [[0.15678473, 0.69662343, 0.75658364],
        [0.82043192, 0.810045  , 0.11737452],
        [0.90799032, 0.04251439, 0.12049618]]])

In [70]:
# 11 Reverse a vector (first element becomes last)
arr = np.arange(10)
print('Orignal Array')
print(arr)
rev_arr = np.flip(arr)
print('Reversed Array')
print(rev_arr)

Orignal Array
[0 1 2 3 4 5 6 7 8 9]
Reversed Array
[9 8 7 6 5 4 3 2 1 0]


In [84]:
# 11 Reverse a vector (first element becomes last)
# https://numpy.org/doc/stable/reference/generated/numpy.flip.html
arr = np.arange(32).reshape(2,4,4)
print('--------ORIGNAL----------')
print(arr)
rev_arr = np.flip(arr)
print('-----WITHOUT AXIS PARAMS------')
print(rev_arr)
rev_arr_0 = np.flip(arr,0)
print('--------DEPTH WISE----------')
print(rev_arr_0)
rev_arr_1 = np.flip(arr,1)
print('--------ROW WISE----------')
print(rev_arr_1)
rev_arr_1 = np.flip(arr,2)
print('--------COLUMN WISE----------')
print(rev_arr_1)

--------ORIGNAL----------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
-----WITHOUT AXIS PARAMS------
[[[31 30 29 28]
  [27 26 25 24]
  [23 22 21 20]
  [19 18 17 16]]

 [[15 14 13 12]
  [11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]
--------DEPTH WISE----------
[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]
--------ROW WISE----------
[[[12 13 14 15]
  [ 8  9 10 11]
  [ 4  5  6  7]
  [ 0  1  2  3]]

 [[28 29 30 31]
  [24 25 26 27]
  [20 21 22 23]
  [16 17 18 19]]]
--------COLUMN WISE----------
[[[ 3  2  1  0]
  [ 7  6  5  4]
  [11 10  9  8]
  [15 14 13 12]]

 [[19 18 17 16]
  [23 22 21 20]
  [27 26 25 24]
  [31 30 29 28]]]


In [87]:
# 12 - Create a null vector of size 10 but the fifth value which is 1
x = np.zeros(10, dtype=int)
x[4] = 1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [98]:
# 13 - Create a 3x3 identity matrix
# https://numpy.org/doc/stable/reference/generated/numpy.identity.html
x = np.identity(3, dtype=int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [103]:
# 14 - Change data type from int to float. arr = np.array([1, 2, 3, 4, 5])
arr = np.array([1, 2, 3, 4, 5], dtype= float)
arr

array([1., 2., 3., 4., 5.])

In [105]:
 # 15 - Multiplication of Arrays
    
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
product_arr = arr1 * arr2
product_arr

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [108]:
# 16 - Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
comparision = arr1 == arr2
new_arr = comparision.all()
print(comparision)
print(new_arr)


[[False False False]
 [False False False]]
False


In [112]:
# 16 - Make an array by comparing both the arrays provided above
x = np.arange(4)
y = np.arange(4)
com = x == y
print(com)
print('isArraysEquals =' , com.all())

[ True  True  True  True]
isArraysEquals = True


In [113]:
# 17 - Extract all odd numbers from arr with values(0-9)
x = np.arange(10)
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

In [115]:
# 18 - Replace all odd numbers to -1 from previous array
x [x % 2 == 1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [118]:
# 19 - Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [124]:
# 20 - Create a 2d array with 1 on the border and 0 inside
two_d_arr = np.ones(16, dtype= int).reshape(4,4)
two_d_arr[1:3,1:3] = 0
two_d_arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [129]:
# 20 - Create a 2d array with 1 on the border and 0 inside
two_d_arr = np.ones(45, dtype= int).reshape(9,5)
two_d_arr[1:8,1:4] = 0
two_d_arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [131]:
# 21 - Replace the value 5 to 12
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1:2,1:2] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [133]:
# 21 - Replace the value other than 5 to 12 (bare operator just for practice)
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[:] = 12
arr2d[1:2,1:2] = 5
arr2d

array([[12, 12, 12],
       [12,  5, 12],
       [12, 12, 12]])

In [136]:
# 22 - Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [14]:
# 23 - Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it
arr_2d = np.arange(10).reshape(2,5)
print(arr_2d)
arr_2d[0:1,:]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[0, 1, 2, 3, 4]])

In [16]:
# 24 - Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it
arr_2d = np.arange(10).reshape(2,5)
print(arr_2d)
arr_2d[1:2,1:2]


[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[6]])

In [18]:
# 25 - Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows
arr_2d = np.arange(10).reshape(2,5)
print(arr_2d)
arr_2d[:, 2:3]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([[2],
       [7]])

In [36]:
# 26 - Create a 10x10 array with random values and find the minimum and maximum values
rand_arr = np.random.rand(100).reshape(10,10)
print('orignal array is')
print(rand_arr)
print('min value is',rand_arr.min())
print('max value is',rand_arr.max())

orignal array is
[[0.91355867 0.59505912 0.52049096 0.46587488 0.08618671 0.90115137
  0.18042665 0.36721074 0.77230244 0.23714914]
 [0.24152488 0.5424542  0.51750683 0.05303089 0.21833889 0.73615699
  0.63275143 0.80958661 0.54947298 0.55266235]
 [0.90023938 0.79191431 0.00141912 0.42988357 0.62451999 0.26934526
  0.72057256 0.84130555 0.70638    0.42437623]
 [0.1819006  0.35708851 0.45180328 0.84036387 0.75145611 0.43070242
  0.9787761  0.94579606 0.01852585 0.60293324]
 [0.18628081 0.0745827  0.73685182 0.99117234 0.7309421  0.08945509
  0.92685452 0.85701012 0.023939   0.88648326]
 [0.07742167 0.05694591 0.00698012 0.04505398 0.86888207 0.56040573
  0.83159541 0.32572826 0.4903411  0.04491595]
 [0.63960354 0.92919336 0.81513077 0.04704099 0.39582248 0.55562368
  0.59721265 0.43186547 0.95703492 0.37004377]
 [0.44714261 0.40127401 0.59409852 0.88787842 0.2843205  0.19317591
  0.64017495 0.74928394 0.86335905 0.11793294]
 [0.97587359 0.9557789  0.26734739 0.2099186  0.20553689 0.4317

In [38]:
# 27 - Find the common items between a and b
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b) # https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html
common_items

array([2, 4])

In [44]:
# 28 - Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b , return_indices=True)
common_items

(array([2, 4]), array([1, 5], dtype=int64), array([1, 5], dtype=int64))

In [45]:
# 28 - Find the positions where elements of a and b match
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,0,10,2,7,0,9,4,9,8])
common_indices = np.intersect1d(a,b, return_indices=True)
common_indices

(array([2, 4]), array([1, 5], dtype=int64), array([3, 7], dtype=int64))

In [55]:
# 29 - Find all the values from array data where the values from array names are not equal to Will
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = names != 'Will'
print(mask)
data[mask]

[ True  True False  True False  True  True]


array([[-1.4516847 , -1.37942199, -0.85437413,  0.02127595],
       [ 1.06762528, -0.99198121,  0.89859057,  0.16024106],
       [-3.28052391,  0.22728993,  1.95606625,  0.54262439],
       [-0.81107349, -0.89183468,  0.96105595, -1.06892198],
       [-1.81917641, -0.70458202,  0.13226239,  0.37087915]])

In [54]:
# 30 - Find all the values from array data where the values from array names are not equal to Will and Joe
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
mask = (names != 'Will') & (names != 'Joe')
print(mask)
data[mask]

[ True False False  True False False False]


array([[ 0.57613609,  0.36881912,  0.5623586 , -0.57421729],
       [ 0.73775225, -1.46372375, -1.03333689, -0.41828064]])

In [56]:
# 31 - Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.
two_d_arr = np.arange(1,16).reshape(5,3)
two_d_arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [57]:
# 32 - Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.
three_d_arr = np.arange(1,17).reshape(2,2,4)
three_d_arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

In [75]:
# 33 - Swap axes of the array you created in Question 32
three_d_arr.swapaxes(1,2) # https://numpy.org/doc/stable/reference/generated/numpy.swapaxes.html

array([[[ 1,  5],
        [ 2,  6],
        [ 3,  7],
        [ 4,  8]],

       [[ 9, 13],
        [10, 14],
        [11, 15],
        [12, 16]]])

In [85]:
# 34 - Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0
arr = np.random.rand(10)
sqrt_arr = np.sqrt(arr) # https://numpy.org/doc/stable/reference/generated/numpy.sqrt.html
sqrt_arr[sqrt_arr < .5] = 0
sqrt_arr

array([0.88760815, 0.63081287, 0.6004832 , 0.52806609, 0.97233085,
       0.67448387, 0.93272107, 0.54924501, 0.72666316, 0.95712908])

In [96]:
# 35 - Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays
x = np.random.rand(12)
y = np.random.rand(12)
res = np.array([x.max(), y.max()])
print(x)
print('-------------------------------------------------------------------')
print(y)
print('-------------------------------------------------------------------')
print('Array of Max Numbers of Both Arrays',res)



[0.3036315  0.82274183 0.60182166 0.29259655 0.7595963  0.55958659
 0.49026742 0.88132891 0.49576594 0.33454351 0.61195616 0.90476714]
-------------------------------------------------------------------
[0.42484506 0.32424471 0.19092188 0.29103706 0.86477239 0.20561351
 0.42019885 0.89365344 0.22047848 0.51946487 0.92113109 0.78981422]
-------------------------------------------------------------------
Array of Max Numbers of Both Arrays [0.90476714 0.92113109]


In [103]:
# 36 - Find the unique names and sort them out!
names = np.array(['Will','Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unq_arr = np.unique(names) # https://numpy.org/doc/stable/reference/generated/numpy.unique.html
print(unq_arr)
print('It seems unique method is returning after sorting')
sorted_arr = np.sort(unq_arr) # https://numpy.org/doc/stable/reference/generated/numpy.sort.html
sorted_arr

['Bob' 'Joe' 'Will']


array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [117]:
# 37 - From array a remove all items present in array b
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
commonElement = np.intersect1d(a,b, return_indices=True)
indexOfCommonElementInFirstArray = commonElement[1][0]
result = np.delete(a,indexOfCommonElementInFirstArray ) # https://numpy.org/doc/stable/reference/generated/numpy.delete.html
result

array([1, 2, 3, 4])

In [126]:
# 38 - Following is the input NumPy array delete column two and insert following new column in its place
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
deletedColumnArray = np.delete(sampleArray, 1,1) # https://numpy.org/doc/stable/reference/generated/numpy.delete.html
newColumn = np.array([[10,10,10]])
result = np.insert(deletedColumnArray,1, newColumn,1) # https://numpy.org/doc/stable/reference/generated/numpy.insert.html
result

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

In [130]:
# 39 - Find the dot product of the above two matrix
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
# https://numpy.org/doc/stable/reference/generated/numpy.dot.html
np.dot(x, y)  # syntax no 1
x.dot(y) # syntax no 2
x @ y  # syntax no 3


array([[ 28.,  64.],
       [ 67., 181.]])

In [153]:
# 40 Generate a matrix of 20 random values and find its cumulative sum
arr = np.random.rand(20)
print('RANDOM NUMBERS')
print(arr)
print('\n')
print('CUMULATIVE SUM OF RANDOM NUMBERS')
print(np.cumsum(arr)) # https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html
print('\n')
arr = np.arange(10).reshape(2,5)
print('MORE DETAILS ABOUT CUMULATIVE SUM')
print('\n')
print('-------------orignal array----------')
print(arr)
print('\n')
print('------------cumulative sum ----------')
print(np.cumsum(arr))
print('\n')
print('------row wise cumulative sum -------')
print(np.cumsum(arr, axis = 0))
print('\n')
print('------column wise cumulative sum -----')
print(np.cumsum(arr,axis = 1))

RANDOM NUMBERS
[0.70764162 0.2499761  0.13539197 0.85006263 0.09993694 0.2717776
 0.94359374 0.84341182 0.28897987 0.37596775 0.623805   0.03175917
 0.17986038 0.98059868 0.52248607 0.04257052 0.91726684 0.32006053
 0.18153451 0.58263469]


CUMULATIVE SUM OF RANDOM NUMBERS
[0.70764162 0.95761772 1.09300969 1.94307231 2.04300925 2.31478686
 3.25838059 4.10179242 4.39077229 4.76674004 5.39054504 5.42230421
 5.60216458 6.58276326 7.10524933 7.14781986 8.0650867  8.38514723
 8.56668174 9.14931643]


MORE DETAILS ABOUT CUMULATIVE SUM


-------------orignal array----------
[[0 1 2 3 4]
 [5 6 7 8 9]]


------------cumulative sum ----------
[ 0  1  3  6 10 15 21 28 36 45]


------row wise cumulative sum -------
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]]


------column wise cumulative sum -----
[[ 0  1  3  6 10]
 [ 5 11 18 26 35]]
