In [1]:
print('Hello World')

Hello World


In [2]:
print('Can I go on Git Hub Repo')

Can I go on Git Hub Repo


In [3]:
# 1 - Import the numpy package under the name np
import numpy as np

In [5]:
# 2 - Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 2 - Create a null vector of size 10 (Let's try to change its data type)
null_vector = np.zeros(10, dtype= int)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# 3 - Create a vector with values ranging from 10 to 49
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# 4 - Find the shape of previous array in question 3
x.shape

1

In [23]:
# 5 - Print the type of the previous array in question 3
x.dtype

dtype('int32')

In [30]:
# 6 - Print the numpy version and the configuration
print('Numpy version is',np.__version__)
print(np.show_config())

Numpy version is 1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


In [31]:
# 7 - Print the dimension of the array in question 3
x.ndim

1

In [38]:
# 8 - Create a boolean array with all the True values
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [40]:
# 9 - Create a two dimensional array
two_d_arr = np.arange(10).reshape(2,5)
two_d_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
# 9 - Create a two dimensional array
two_d_arr = np.array([[1,2,3,4,5],[11,22,33,44,55]])
two_d_arr

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [45]:
# 9 - Create a two dimensional array
x = np.arange(10)
x
y = np.arange(10,20)
y
two_d_arr = np.array([x,y])
two_d_arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [53]:
# 9 - Create a two dimensional array
x = np.random.rand(10).reshape(2,5)
x

array([[0.95553775, 0.51964908, 0.22350665, 0.81285491, 0.60640809],
       [0.80377518, 0.38697976, 0.64625894, 0.30863401, 0.82516182]])

In [54]:
# 10 - Create a three dimensional array
three_d_arr = np.arange(8).reshape(2,2,2)
three_d_arr


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [61]:
# 10 - Create a three dimensional array
three_d_arr = np.array([ [[1,2,3],[4,5,6]], [[6,5,4],[3,2,1]] ])
three_d_arr

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [62]:
# 10 - Create a three dimensional array
three_d_arr = np.random.rand(27).reshape(3,3,3)
three_d_arr

array([[[0.59409984, 0.18378778, 0.01446873],
        [0.0275978 , 0.28873459, 0.87136217],
        [0.05968443, 0.33016941, 0.95182061]],

       [[0.56502682, 0.15803391, 0.22493604],
        [0.27812862, 0.7063894 , 0.11457672],
        [0.06437019, 0.30913878, 0.38537361]],

       [[0.15678473, 0.69662343, 0.75658364],
        [0.82043192, 0.810045  , 0.11737452],
        [0.90799032, 0.04251439, 0.12049618]]])

In [70]:
# 11 Reverse a vector (first element becomes last)
arr = np.arange(10)
print('Orignal Array')
print(arr)
rev_arr = np.flip(arr)
print('Reversed Array')
print(rev_arr)

Orignal Array
[0 1 2 3 4 5 6 7 8 9]
Reversed Array
[9 8 7 6 5 4 3 2 1 0]


In [84]:
# 11 Reverse a vector (first element becomes last)
arr = np.arange(32).reshape(2,4,4)
print('--------ORIGNAL----------')
print(arr)
rev_arr = np.flip(arr)
print('-----WITHOUT AXIS PARAMS------')
print(rev_arr)
rev_arr_0 = np.flip(arr,0)
print('--------DEPTH WISE----------')
print(rev_arr_0)
rev_arr_1 = np.flip(arr,1)
print('--------ROW WISE----------')
print(rev_arr_1)
rev_arr_1 = np.flip(arr,2)
print('--------COLUMN WISE----------')
print(rev_arr_1)

--------ORIGNAL----------
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]
-----WITHOUT AXIS PARAMS------
[[[31 30 29 28]
  [27 26 25 24]
  [23 22 21 20]
  [19 18 17 16]]

 [[15 14 13 12]
  [11 10  9  8]
  [ 7  6  5  4]
  [ 3  2  1  0]]]
--------DEPTH WISE----------
[[[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]]
--------ROW WISE----------
[[[12 13 14 15]
  [ 8  9 10 11]
  [ 4  5  6  7]
  [ 0  1  2  3]]

 [[28 29 30 31]
  [24 25 26 27]
  [20 21 22 23]
  [16 17 18 19]]]
--------COLUMN WISE----------
[[[ 3  2  1  0]
  [ 7  6  5  4]
  [11 10  9  8]
  [15 14 13 12]]

 [[19 18 17 16]
  [23 22 21 20]
  [27 26 25 24]
  [31 30 29 28]]]


In [87]:
# 12 - Create a null vector of size 10 but the fifth value which is 1
x = np.zeros(10, dtype=int)
x[4] = 1
x

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [98]:
# 13 - Create a 3x3 identity matrix
x = np.identity(3, dtype=int)
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [103]:
# 14 - Change data type from int to float. arr = np.array([1, 2, 3, 4, 5])
arr = np.array([1, 2, 3, 4, 5], dtype= float)
arr

array([1., 2., 3., 4., 5.])

In [105]:
 # 15 - Multiplication of Arrays
    
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])
product_arr = arr1 * arr2
product_arr

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

In [108]:
# 16 - Make an array by comparing both the arrays provided above
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
comparision = arr1 == arr2
new_arr = comparision.all()
print(comparision)
print(new_arr)


[[False False False]
 [False False False]]
False


In [112]:
# 16 - Make an array by comparing both the arrays provided above
x = np.arange(4)
y = np.arange(4)
com = x == y
print(com)
print('isArraysEquals =' , com.all())

[ True  True  True  True]
isArraysEquals = True


In [113]:
# 17 - Extract all odd numbers from arr with values(0-9)
x = np.arange(10)
x[x % 2 == 1]

array([1, 3, 5, 7, 9])

In [115]:
# 18 - Replace all odd numbers to -1 from previous array
x [x % 2 == 1] = -1
x

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [118]:
# 19 - Replace the values of indexes 5,6,7 and 8 to 12
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

In [124]:
# 20 - Create a 2d array with 1 on the border and 0 inside
two_d_arr = np.ones(16, dtype= int).reshape(4,4)
two_d_arr[1:3,1:3] = 0
two_d_arr

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

In [129]:
# 20 - Create a 2d array with 1 on the border and 0 inside
two_d_arr = np.ones(45, dtype= int).reshape(9,5)
two_d_arr[1:8,1:4] = 0
two_d_arr

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [131]:
# 21 Replace the value 5 to 12
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[1:2,1:2] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [133]:
# 21 Replace the value other than 5 to 12 (bare operator just for practice)
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
arr2d[:] = 12
arr2d[1:2,1:2] = 5
arr2d

array([[12, 12, 12],
       [12,  5, 12],
       [12, 12, 12]])

In [136]:
# 22 - Convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])