In [1]:
print('Hello World')

Hello World


In [2]:
print('Can I go on Git Hub Repo')

Can I go on Git Hub Repo


In [3]:
# 1 - Import the numpy package under the name np
import numpy as np

In [5]:
# 2 - Create a null vector of size 10
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# 2 - Create a null vector of size 10 (Let's try to change its data type)
null_vector = np.zeros(10, dtype= int)
null_vector

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# 3 - Create a vector with values ranging from 10 to 49
x = np.arange(10,50)
x


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [12]:
# 4 - Find the shape of previous array in question 3
x.shape

1