In [1]:
print('Hello, I am going to do Assignment No 2')

Hello, I am going to do Assignment No 2


In [3]:
print('Lets put it on GitHub')

Lets put it on GitHub


In [5]:
# 1 - Convert a 1D array to a 2D array with 2 rows
import numpy as np
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
# 2 - How to stack two arrays vertically
arr1 = np.arange(10).reshape(2,5)
print(arr1)
arr2 = np.ones(10).reshape(2,5)
print(arr2)
# https://numpy.org/doc/stable/reference/generated/numpy.vstack.html
np.vstack((arr1, arr2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# 3 - How to stack two arrays horizontally
arr1 = np.arange(10).reshape(2,5)
print(arr1)
arr2 = np.ones(10).reshape(2,5)
print(arr2)
# https://numpy.org/doc/stable/reference/generated/numpy.hstack.html
np.hstack((arr1, arr2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

In [22]:
# 4 - How to convert an array of arrays into a flat 1d array
ndarray = np.arange(10).reshape(2,5)
print(ndarray)
np.ravel(ndarray)

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
# 4 - How to convert an array of arrays into a flat 1d array
ndarray = np.arange(1,82).reshape(3,3,3,3)
print(ndarray)
# https://numpy.org/doc/stable/reference/generated/numpy.ravel.html
np.ravel(ndarray)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]]

  [[10 11 12]
   [13 14 15]
   [16 17 18]]

  [[19 20 21]
   [22 23 24]
   [25 26 27]]]


 [[[28 29 30]
   [31 32 33]
   [34 35 36]]

  [[37 38 39]
   [40 41 42]
   [43 44 45]]

  [[46 47 48]
   [49 50 51]
   [52 53 54]]]


 [[[55 56 57]
   [58 59 60]
   [61 62 63]]

  [[64 65 66]
   [67 68 69]
   [70 71 72]]

  [[73 74 75]
   [76 77 78]
   [79 80 81]]]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81])

In [24]:
# 5 - How to Convert higher dimension into one dimension
ndarray = np.arange(15).reshape(3,5)
print(ndarray)
np.ravel(ndarray)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
# 6 - Convert one dimension to higher dimension
arr = np.arange(15)
print(arr)
arr.reshape(5,3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [34]:
# 7 - Create 5x5 an array and find the square of an array
arr = np.arange(25).reshape(5,5)
print(arr)
prod_arr = arr * arr
print('\n')
print('Product of array is')
print(prod_arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


Product of array is
[[  0   1   4   9  16]
 [ 25  36  49  64  81]
 [100 121 144 169 196]
 [225 256 289 324 361]
 [400 441 484 529 576]]


In [33]:
# 8 - Create 5x6 an array and find the mean
arr = np.arange(30).reshape(5,6)
print(arr)
# https://numpy.org/doc/stable/reference/generated/numpy.mean.html
mean = np.mean(arr)
print('\n')
print('Mean of array is')
print(mean)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


Mean of array is
14.5


In [36]:
# 9 - Find the standard deviation of the previous array in Q8
standard_deviation = np.std(arr)# https://numpy.org/doc/stable/reference/generated/numpy.std.html
print('Standard Deviation of array is')
print(standard_deviation)

Standard Deviation of array is
7.211102550927978


In [38]:
# 10 - Find the median of the previous array in Q8
median = np.median(arr)# https://numpy.org/doc/stable/reference/generated/numpy.median.html#:~:text=If%20out%20is%20specified%2C%20that%20array%20is%20returned%20instead.&text=Given%20a%20vector%20V%20of,V_sorted%20when%20N%20is%20even.
print('Median of array is')
print(median)

Median of array is
12.0


In [40]:
# 11 - Find the transpose of the previous array in Q8
transpose = np.transpose(arr)# https://numpy.org/doc/stable/reference/generated/numpy.transpose.html
print('Transpose of array is')
print(transpose)

Transpose of array is
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [53]:
# 12 - Create a 4x4 an array and find the sum of diagonal elements
arr = np.arange(1,17).reshape(4,4)
print(arr)
print('\n')
print('diagonal elements are')
print(arr.diagonal()) # https://numpy.org/doc/stable/reference/generated/numpy.diagonal.html
print('\n')
print('product of diagonal elements is')
print(arr.diagonal().prod())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


diagonal elements are
[ 1  6 11 16]


product of diagonal elements is
1056


In [54]:
# 13 - Find the determinant of the previous array in Q12
np.linalg.det(arr)

0.0

In [59]:
# 14 Find the 5th and 95th percentile of an array
arr = np.arange(1,101)
# https://numpy.org/doc/stable/reference/generated/numpy.percentile.html#:~:text=Compute%20the%20q%2Dth%20percentile,s)%20of%20the%20array%20elements.&text=If%20True%2C%20then%20allow%20the,intermediate%20calculations%2C%20to%20save%20memory.
percentile = np.percentile(arr, 5)
print('5 th percentile is')
print(percentile)
print('\n')
percentile = np.percentile(arr, 95)
print('95 th percentile is')
print(percentile)

5 th percentile is
5.95


95 th percentile is
95.05


In [82]:
# 15 - How to find if a given array has any null values
arr = np.array([4.,6,7,3,8,56,23])
arrr = np.insert(arr,2,np.NaN)
sum_arr = np.sum(arrr)
nan = np.isnan(sum_arr)
if (nan == True):
    print('Yes, We have NaN in the array')
else:
    print('No, We dont have NaN in the array')    


Yes, We have NaN in the array
